### ISSUE TITLE
Outsource regexes?

### ISSUE THREAD

**Issue by Myzel394** [crisp-oss/email-forward-parser#11]
In regard to #10 I think it would be very beneficial if the regexes would be outsourced to a single repo focused only on them. This would allow developers to use and update them more easily (which will also help you! :D).

To integrate them into other apps one may download them for example on a nightly basis via ci:cd and include them into their package.

What do you think? I'd be very happy about it! :)

**Comment by Myzel394** [comment]
@eliottvincent what do you think?

**Comment by eliottvincent** [comment]
Hey @Myzel394 ! I agree this is a great idea, however I have no plans of doing this right now :) Maybe in the future.

For now the regexes are stable so you can simply copy paste them in your own project. I agree this is not ideal, but it works just fine.
