### ISSUE TITLE
Go port

### ISSUE THREAD

**Issue by darnfish** [crisp-oss/email-forward-parser#15]
Hey there,

Not an issue, I ported this library to Go :~) there's like two places that still need to be ported but works 99% of the time.

https://github.com/darnfish/email-forward-parser

**Comment by eliottvincent** [comment]
Hey, that's really cool! What do you plan to use it for?

**Comment by darnfish** [comment]
I'm building an iOS app and the backend is in Go, it's a nicer way to keep track of Amazon Locker codes.

An auto-forwarding rule would forward emails from Amazon to an SMTP server on the backend, and then `email-forward-parser` would extract the original from and body for verification and more regexing to get details out.

I just updated the repo, all tests are passing! Thank you for your work on this, I can tell it must've been difficult haha.
