### ISSUE TITLE
Cannot find module './build/Release/re2.node'

### ISSUE THREAD

**Issue by BuslovSirin** [crisp-oss/email-forward-parser#16]
Good day to everyone!
I ran this in js file with `node file-ex.js `

```
const EmailForwardParser = require("./email-forward-parser");
const result = new EmailForwardParser().read(MY_EMAIL_STRING, MY_SUBJECT_STRING);
console.log(result);
```

And got the error below:

Error: Cannot find module './build/Release/re2.node'
Require stack:
- C:\Users\dmitry\Desktop\email-forward-parser\node_modules\re2\re2.js
- C:\Users\dmitry\Desktop\email-forward-parser\lib\parser.js
- C:\Users\dmitry\Desktop\email-forward-parser\lib\index.js
- C:\Users\dmitry\Desktop\file-ex.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (C:\Users\dmitry\Desktop\email-forward-parser\node_modules\re2\re2.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\dmitry\\Desktop\\email-forward-parser\\node_modules\\re2\\re2.js',
    'C:\\Users\\dmitry\\Desktop\\email-forward-parser\\lib\\parser.js',
    'C:\\Users\\dmitry\\Desktop\\email-forward-parser\\lib\\index.js',
    'C:\\Users\\dmitry\\Desktop\\file-ex.js'
  ]
}

**Comment by eliottvincent** [comment]
Hey!

The line `require("./email-forward-parser");` makes me think that you didn't install the library via npm.
This means that the required dependencies (`re2`) were not installed, hence the error.

So in that case, you need to manually install the required dependencies:

```js
cd ./email-forward-parser
npm i
```

**Comment by BuslovSirin** [comment]
Thank you for a quick answer. Unfortunately, after installation of these commands i still bump into the error below
```
> re2@1.20.3 install C:\Users\dmitry\Desktop\email-forward-parser\node_modules\re2
> install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild

Trying https://github.com/uhop/node-re2/releases/download/1.20.3/win32-x64-83.br ...
Trying https://github.com/uhop/node-re2/releases/download/1.20.3/win32-x64-83.gz ...
Building locally ...

> re2@1.20.3 rebuild C:\Users\dmitry\Desktop\email-forward-parser\node_modules\re2
> node-gyp rebuild


C:\Users\dmitry\Desktop\email-forward-parser\node_modules\re2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
```

I dived into the problem, and due to this problem [node-gyp installation problem](https://stackoverflow.com/questions/33896511/npm-install-fails-with-node-gyp), it's hard to install node-gyp on Windows.
So I'll try to do it in Docker container

**Comment by BuslovSirin** [comment]
Good [Github repo](https://github.com/cmuth001/Dockerizing-a-NodeJS-web-app) to create simple API in Docker and start fast

**Comment by BuslovSirin** [comment]
Unfortunately, still can't install this library. I downloaded VM Ubuntu. When install re2 manually, it writes:

```
dmitry@dmitry:~/Desktop/email-fwd/node_modules/re2$ npm run install

> re2@1.20.3 install
> install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild

Trying https://github.com/uhop/node-re2/releases/download/1.20.3/linux-x64-72.br ...
Trying https://github.com/uhop/node-re2/releases/download/1.20.3/linux-x64-72.gz ...
Building locally ...

> re2@1.20.3 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@12.22.9 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack /home/dmitry/Desktop/email-fwd/node_modules/minipass-fetch/node_modules/minipass/dist/cjs/index.js:286
gyp ERR! stack         this.emit('abort', this[SIGNAL]?.reason);
gyp ERR! stack                                         ^
gyp ERR! stack 
gyp ERR! stack SyntaxError: Unexpected token '.'
gyp ERR! stack     at wrapSafe (internal/modules/cjs/loader.js:915:16)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:963:27)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:863:32)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:887:19)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:74:18)
gyp ERR! stack     at Object.<anonymous> (/home/dmitry/Desktop/email-fwd/node_modules/minipass-fetch/lib/index.js:6:22)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:999:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
gyp ERR! System Linux 6.2.0-32-generic
gyp ERR! command "/usr/bin/node" "/home/dmitry/Desktop/email-fwd/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/dmitry/Desktop/email-fwd/node_modules/re2
gyp ERR! node -v v12.22.9
gyp ERR! node-gyp -v v9.4.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
(node:7629) UnhandledPromiseRejectionWarning: 7
(node:7629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

Have you faced this error before?

**Comment by BuslovSirin** [comment]
After trial and errors, much searching on the Internet there's a solution: use **Node version > 16**
On Windows I've got 14? on Ubuntu 12. None of these worked. After installing Node 16 it finally worked.
Thanks for your efforts to help!

**Comment by eliottvincent** [comment]
Glad you found the issue! I'll enforce the minimum required Node version via the package.json
