### ISSUE TITLE
error while importing package

### ISSUE THREAD

**Issue by gagandt** [crisp-oss/email-forward-parser#6]
I'm trying to use this package but my builds fail with the following error:
```
ERROR in ../../email-forward-parser/node_modules/re2/re2.js 3:12-42
Module not found: Error: Can't resolve './build/Release/re2' in './node_modules/email-forward-parser/node_modules/re2'
 @ ../../email-forward-parser/lib/parser.js 4:34-48
 @ ../../email-forward-parser/lib/index.js 4:13-32

webpack compiled with 1 error
Environment: darwin, node 14.19.1,
```

**Comment by aravindballa** [comment]
could you resolve this?

**Comment by eliottvincent** [comment]
Hello @aravindballa ! When does this error happens? What is your environment?

**Comment by aravindballa** [comment]
I'm on M1 Mac running node v16 (with npm).

I'm trying to import this in a [Remix](https://github.com/remix-run/blues-stack) project.

**Comment by baptistejamin** [comment]
Do you have any error logs when you npm install?Sent from my iPhoneOn 20 Nov 2022, at 06:42, Aravind Balla ***@***.***> wrote:﻿
I'm on M1 Mac running node v16 (with npm).
I'm trying to import this in a Remix project.

**Comment by eliottvincent** [comment]
Inactive, closing.
